### ISSUE TITLE
PositiveFloat is not supported

### ISSUE THREAD

**Issue by Lazloo** [jpmorganchase/py-avro-schema#23]
I use the PositiveFloat Fields in my pydantic model

```python
from pydantic import PositiveFloat
class ModelExample(BaseModel):
    price: PositiveFloat
```

However, this seems not yet supported by py-avro-schema: 

```
TypeError: Cannot generate Avro schema for Python type <class 'pydantic.types.PositiveFloat'>
```

**Comment by faph** [comment]
I guess with respect to Avro schemas this should map to a `double` type? https://py-avro-schema.readthedocs.io/en/stable/types.html#float

**Comment by faph** [comment]
@Lazloo Could you please confirm that this test reproduces the issue and defines the expected behavior?

**Comment by Lazloo** [comment]
Assume you mean [https://github.com/jpmorganchase/py-avro-schema/pull/24/commits/6f0745d10f8115e2caaeb7488b255a1876c475b4](url)

Yes! This describes the issue

**Comment by faph** [comment]
@Lazloo This PR should allow you to use types like `pydantic.PositiveFloat`: PR #24. We will release this on Monday.

**Comment by faph** [comment]
@Lazloo version 1.1.0 now released at https://pypi.org/project/py-avro-schema/
