### ISSUE TITLE
Avro Logical Type "DATE" is not compatible with Pydantic Date definition

### ISSUE THREAD

**Issue by Lazloo** [jpmorganchase/py-avro-schema#28]
I am currently facing the issue that data compliant with the AVRO Schema cannot be handled with Pydantic. E.g. I have a data model

```
import datetime
from aifora.da.schema.customer.models._base import BaseModel
class MyModel(BaseModel):
   start_date: datetime.date 
```

Which returns in the Avro Schema (using py-avro-schema):
```
    {
      "name": "start_date",
      "type": {
        "type": "int",
        "logicalType": "date"
      },
    },
```

According to the [AVRO Specification](https://avro.apache.org/docs/1.8.0/spec.html#Date) date is the number of days after 01/01/1970. However, Pydantic is not accepting this (always leads to `datetime.date(1970, 1, 1)`). Rather seconds or milliseconds (logicalType: `Time` ) are expected. [Pydanitc Datetypes](https://pydantic-docs.helpmanual.io/usage/types/#datetime-types)

**Comment by faph** [comment]
Yep, that's entirely expected. The Avro specification is pretty clear on this.

That you cannot initialize a Pydantic model object's date field with the Avro integer value, that is a different issue. Pydantic has lots of magic support for type casting. So Pydantic just does a best guess what your integer is supposed to mean.

The serialization/deserialization to and from Avro into Python objects, including Pydantic models is not the responsibility of **py-avro-schema**.
