### ISSUE TITLE
Request: allow pydantic option to get field names by alias

### ISSUE THREAD

**Issue by dabdada** [jpmorganchase/py-avro-schema#53]
Hi it would be great if an option would be introduced to render the schema from a pydantic class by field aliases instead of names.

I would be happy to provide a pull request for this.

**Comment by faph** [comment]
Thanks! Yes that looks like a sensible enhancement. Let me review in detail on Monday.

**Comment by dabdada** [comment]
Thank you. As data classes already use the field name it is unfortunately quite pydantic specific and branded.

Anyways this project has bean a pleasure to understand. Very nice and though through code. Thanks a lot.

**Comment by faph** [comment]
Many thanks for this! Released as v3.1.0
