### ISSUE TITLE
Request: use fastavro

### ISSUE THREAD

**Issue by dabdada** [jpmorganchase/py-avro-schema#55]
Is there a way to support fastavro? Can avro be replaced by this or do both libs need to be supported? Why is avro used not fastavro?

**Comment by dabdada** [comment]
Ah sorry just saw this is used in tests only. Nevermind 🙈

**Comment by faph** [comment]
@dabdada It's not just used in tests though. We use the `avro` package for their schema data structures (Python classes) as it seems decent.

Of course, you're welcome to install `fastavro` alongside to the actual serialization/deserialization. That's what I would recommend.
