### ISSUE TITLE
[QUESTION]: DecimalType assignment type linter error

### ISSUE THREAD

**Issue by dada-engineer** [jpmorganchase/py-avro-schema#57]
Hi there,

in vs code the following decimal type assignment (according to docs) creates a typing issue. Is this something that can be resolved in this project? 🤔 

```
from decimal import Decimal
import py_avro_schema as pas

foo: pas.DecimalType[512, 255] = Decimal(10)
```

Pylance error:
```
Expression of type "Decimal" cannot be assigned to declared type "DecimalType"
  "Decimal" is incompatible with "DecimalType"
```

Python Version: 3.11.4
py-avor-schema Version: 3.2.0

**Comment by faph** [comment]
I think we noticed this too. I believe mypy does it correct but that does not help much. 

We should be moving to Python’s new Annotated types. That’s what that is for after all.

**Comment by dabdada** [comment]
Would be great yes

**Comment by faph** [comment]
@dabdada I have started this ^^^ PR for this issue
